### ISSUE TITLE
Miguel Feedback on V0.40?

### ISSUE THREAD

**Issue by shervine** [USfoundation/foundation-web-app#68]
@grumo I created this card for you to share your feedback on the latest version.

**Comment by grumo** [comment]
- Make URLs clickable
- Make all outbound links open on new window (target=“_blank”)
- Auto embed YouTube videos
- Make it easier to add Urls
  - Grab URL metadata automatically (title, thumbnail)
- Label different sections within a node 
  - Now we have the Title, below metadata and below links to other nodes
  - The nodes are now mixed of @, #, !, & - Should we restrict this area to #Goals only?
- Clear input box after an element is added
- Why the “Add Link” pop ups when adding from the “New node: input box?
- After saving without changes, you can’t edit the value
- Can’t enter line breaks inside descriptions
- Adding a sub #Goal should require adding supporting &Source. Otherwise how do we know is a credible goal?
- “New node” legend should be changes to something less generic
- Parenting of URLs is confusing
  - Sometimes you can link and [URL](http://us.foundation/221) to a source or to a [!URL](http://us.foundation/226)

**Comment by grumo** [comment]
Feedback Video: [https://drive.google.com/file/d/0B9hYVpyjxHXTY3RranVtcW0ycWc/view](https://drive.google.com/file/d/0B9hYVpyjxHXTY3RranVtcW0ycWc/view)

**Comment by shervine** [comment]
@grumo Most of these changes would be launched in V0.50 this Wednesday.

Looking forward to your feedback on that version.
